# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: students_api
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/students
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SERVER_ERROR_INCLUDE_MESSAGE=always
    networks:
      - spring-postgres

  db:
    container_name: students_db
    image: postgres:15-alpine
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  postgres-data:

networks:
  spring-postgres:
    driver: bridge
